keptn-contrib/prometheus-service

- eventhandling/configureEvent.go
otherwise the alert manager might send out alerts before a remediation actions effect can become apparent
> #1185 increase duration of alert

- deploy/service.yaml
- main.go
- utils/utils.go
The prometheus-service also listens on Port 8081, which is the default port of the distributor. This lead to the distributor crashing because that port was already in use. This PR sets the port for the distributor to 8082
> Fixed port settings

- eventhandling/alertEvent.go
- eventhandling/configureEvent.go
- go.mod
- go.sum
The name for the scrape jobs of the direct deployment and the proary deployment were the same and overwrote each other. 
Also, it turned out that SLI queries were still retrieved from a ConfigMap, instead of the `prometheus/sli.yaml` file.
This is fixed with this PR
Signed-off-by: Florian Bacher <florian.bacher@dynatrace.com>
> Added scrape job config for primary deployment

- README.md
- deploy/service.yaml
- skaffold.yaml
This PR ensures that the correct distributor image is used for Keptn 0.8.0-alpha, as well as change the docker org to keptncontrib (needed after PR https://github.com/keptn-contrib/prometheus-service/pull/78)
> Fix distributor image and resource requests

- .github/workflows/CI.yml
Based on https://github.com/keptn/keptn/issues/2824 this PR introduces a new GH action for extracting the branch name, therefore reducing the CI workflows complexity within this repository.
> Use keptn/gh-action-extract-branch-name

- README.md
Update Prometheus-service readme with the new enhancement
Signed-off-by: Raj Das <mail.rajdas@gmail.com>
**Preview**
[![Build Status](https://travis-ci.org/keptn-contrib/prometheus-service.svg?branch=master)](https://travis-ci.org/keptn-contrib/prometheus-service)
[![Go Report Card](https://goreportcard.com/badge/github.com/keptn-contrib/prometheus-service)](https://goreportcard.com/report/github.com/keptn-contrib/prometheus-service)
The *prometheus-service* is a [Keptn](https://keptn.sh) service that is responsible for
1. configuring Prometheus for monitoring services managed by Keptn, and
1. receiving alerts from Prometheus Alertmanager and translating the alert payload to a cloud event that is sent to the Keptn eventbroker.
Please always double check the version of Keptn you are using …
> Update Prometheus-service readme with the new enhancement

- deploy/service.yaml
- eventhandling/alertEvent.go
- eventhandling/configureEvent.go
- trigger_remediation.json
This PR fixes:
- the Alerting rules have been added to the wrong place in the ConfigMap
- send a `sh.keptn.event.remediation.triggered` event instead of a `problem.opened`
- the payload of the `remediation.triggered` must look as follows: 
```
{
"type": "sh.keptn.event.production.remediation.triggered",
"specversion": "1.0",
"source": "https://github.com/keptn/keptn/prometheus-service",
"id": "f2b878d3-03c0-4e8f-bc3f-454bc1b3d79d",
"time": "2019-06-07T07:02:15.64489Z",
"contenttype": "application/json",
"data": {
"project": "sockshop",
"stage": "production",
"service": "carts",
"problem": {
"problemTitle": "response_time_p90",
"rootCause": "Response time degradation"
}
}
}
```
> Adaptations to support the auto-remediation UC

- eventhandling/configureEvent.go
- re-introduces the scrape-interval on the level of a scrape-job, rather than globally for prometheus
Fixes #198 and #179
**Note**: I've tested it with 10s (see screenshots), but I've set it to 5s in source code afterwards
> #198 Re-introduce scrape interval of 5s

- eventhandling/configureEvent.go
While in PR https://github.com/keptn-contrib/prometheus-service/pull/199 we introduced a scrape interval, this causes issues without having a proper scrape timeout.
- adds a scrape timeout
> Fix scrape timeout

- deploy/service.yaml
- eventhandling/alertEvent.go
- prometheus_alert.json
- Re-adds shkeptncontext to the remediation.triggered CloudEvents, such that triggering the sequence works again.
- Removes legacy "EVENTBROKER" entries
- Adds prometheus_alert.json as an example alert (e.g., `curl -X POST -H "Content-Type: application/json" -d @prometheus_alert.json http://localhost:8080`)
Fixes #60
Related to #195
> fix(core): fix event sending and added keptncontext (#60)

- .dockerignore
- main.go
- Fixes the event forwarding when a cloudevent is received on port 8080 via the golang http handler
- Updates dockerignore to speed up docker build 
Fixes #195
> fix(core): Fix event forwarding to localhost (#195)

- README.md
- deploy/role.yaml
- deploy/service.yaml
- Prepares for the 0.7.2 release
- Re-introduces role.yaml (and removes it from service.yaml), as those are two separate manifests that need to be applied independently, e.g.:
```
kubectl apply -f https://raw.githubusercontent.com/keptn-contrib/prometheus-service/release-0.7.1/deploy/service.yaml
kubectl apply -f https://raw.githubusercontent.com/keptn-contrib/prometheus-service/release-0.7.1/deploy/role.yaml -n monitoring
```
FYI @solidnerd
> build(release): prepare 0.7.2 release

- Dockerfile
- deploy/service.yaml
- eventhandling/configureEvent.go
- main.go
- utils/utils.go
- removes eventbroker from our codebase as this is no longer available since a couple of keptn versions
- use `SKAFFOLD_GO_GCFLAGS` in Dockerfile for proper debugging flags when using skaffolds
-
> chore: remove eventbroker from code

- eventhandling/configureEvent.go
- utils/prometheus.go
- Removes code for creating the alert manager template, as it already exists if you followed the install instructions for prometheus given in this README
- Added some inline comments to better understand the code
- Moved calls for restarting prometheus within the `if eh.isPrometheusInstalled() {` block 
Fixes #197
> fix(core): alert manager template does not need to be created, it already exists

- renovate.json
Renovate wasn't using semantic commits so far.
According to https://docs.renovatebot.com/semantic-commits/ we just need to add `:semanticCommits` to the extends array
> chore: renovate should use semantic commits

- .github/workflows/CI.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/validate-semantic-pr.yml
- uses the brand new prepare-ci workflow from keptn/gh-automation to reduce lines of code
- updates the respective workflows/actions from keptn/gh-automation to use the latest release tag v1.4.0
> build: update gh workflows to re-use keptn/gh-automation

- README.md
- Fixes README which contained a link to a kubernetes manifest on a branch, rather than a tag
- Updates installation instructions with `helm upgrade`
> fix: installing role and rolebinding from correct tag

- chart/templates/deployment.yaml
- eventhandling/alertEvent.go
- eventhandling/configureEvent.go
- eventhandling/getSliEvent.go
- eventhandling/handler.go
- main.go
* make use of go-utils `eh.keptnHandler.SendTaskFinishedEvent` as much as possible
* make use of go-utils built-in event structs as much as possible
> refactor: use built-in send event functionality of keptn/go-utils

- prometheus_alert.http
I added a helper utilty to test prometheus alerts.
This works nice in JetBrains IDEs, and in VS Code using [Huachao Mao REST Client in VS Code](https://marketplace.visualstudio.com/items?itemName=humao.rest-client).
> chore: added a way to test prometheus alerts

- chart/templates/deployment.yaml
- eventhandling/alertEvent.go
- main.go
- utils/env.go
- Use `cloudevents.WithGetHandlerFunc()` function to implement health checks and alerting endpoint  
- Remove other HTTP Endpoints
- Change `PORT` environment variable
#266
> feat: Use cloudevent for alerting endpoint

- README.md
BREAKING CHANGE: This release requires Keptn 0.14.2 or newer to be installed.
> docs: compatibility with Keptn 0.14.2

- README.md
- chart/templates/serviceaccount.yaml
- eventhandling/getSliEvent.go
- utils/k8s.go
**Changes**
* Implement reading of secrets created via `keptn create secret`
* Update README accordingly
* Removed roles for accessing secrets - this is handled in Keptn secret-service by setting the scope of a secret (it was added in https://github.com/keptn/keptn/pull/6938 )
Fixes #274 
**How to test this:**
```console
PROMETHEUS_USER=test
PROMETHEUS_PASSWORD=test-password
PROMETHEUS_URL=http://prometheus-server.monitoring.svc.cluster.local
keptn create secret prometheus-credentials-<project> --scope="keptn-prometheus-service" --from-literal="PROMETHEUS_USER=$PROMETHEUS_USER" --from-literal="PROMETHEUS_PASSWORD=$PROMETHEUS_PASSWORD" --from-literal="PROMETHEUS_URL=$PROMETHEUS_URL"
```
and trigger a delivery which will do an evaluation (e.g., in `staging`):
```console
keptn trigger …
```
> feat: Use Keptn secrets for storing external prometheus-server URL

- .github/actions/unit-tests/action.yml
- .github/workflows/reviewdog.yml
This PR upgrades setup-go action, and uses the brand new `go-version-file` feature, which lowers our future maintenance efforts for maining the go version in multiple files :)
> build(deps): Upgrade setup-go action to use go.mod as a version file

- README.md
- chart/values.yaml
- go.mod
- go.sum
- skaffold.yaml
- Update distributor to version 0.16.0
- Update `go-utils` to v0.16.0
- Add version to compatibility matrix
> feat: Upgrade to Keptn 0.16

- go.mod
- go.sum
- pins the version of the `github.com/prometheus/common` dependency to the same version that is used in the altermanager
- #318
> fix: Compatibility issues with alertmanager configuration

- README.md
- chart/templates/_helpers.tpl
- chart/templates/deployment.yaml
- chart/values.schema.json
- chart/values.yaml
- Autodetects the prometheus and alertmanager namespaces
- `namespace` and `namespace_am` values are used to overwrite the autodetect
> feat: Autodetect prometheus and alertmanager namespaces

- eventhandling/alertEvent.go
- Fix bug where the remediation-service is unable to find action for problem type default
- Changes `remediation.triggered` cloud event payload to match the [remediation service](https://github.com/keptn/keptn/blob/master/remediation-service/handler/get_action_event_handler.go#L27)
> fix: Alertmanager cloudevent payload

- eventhandling/alertEvent.go
- eventhandling/configureEvent.go
- eventhandling/getSliEvent.go
- go.mod
- go.sum
- test/data/podtatohead.jes-config.yaml
- test/data/podtatohead.remediation.yaml
- test/e2e/podtatohead_test.go
- test/e2e/utils.go
- test/events/prometheus-firing.json
- test/shipyard/podtatohead.deployment.yaml
- ensures that the deployment type "primary" is used if not specified in the cloud event
- the deployment type is saved in the configure step into the alert manager 
- deployment type can be specified by labels
- #354
> fix: Default deployment in alerts/remediations to "primary" if not specified

- .github/workflows/integration-tests.yaml
- README.md
Unfortunately with the introduction of go-utils v0.18.0 (https://github.com/keptn-contrib/prometheus-service/pull/361) we lost compatiblity with Keptn 0.17 and older versions.
This is a breaking change in Keptn, and we need to go forward with it.
Therefore, this PR
* adds Keptn 0.18 to integration tests
* removes older version of Keptn from integration tests
* Added next release of prometheus-service to compatibility matrix
* Added a variable for the GITEA_PROVISIONER_VERSION and set it to the latest release 0.1.1
Fixes #362 
integration test run with 0.18.1 is green: https://github.com/keptn-contrib/prometheus-service/actions/runs/2946696911
> feat!: Keptn 0.18 compatibility

- eventhandling/alertEvent.go
- eventhandling/get_sli_event_handler.go
- prometheus_alert.json
- test/e2e/podtatohead_test.go
- test/shipyard/podtatohead.deployment.yaml
During testing I noticed that our remediation workflow never gets into an evaluation.triggered, unfortunately.
We end up getting an error message in Keptn's lighthouse-service like this:
```
ime="2022-08-29T12:15:49Z" level=error msg="Could not parse event payload: [json] found bytes \"{\"action\":{\"action\":\"scaling\",\"description\":\"Scale up\",\"name\":\"scaling\",\"value\":\"1\"},\"deployment\":\"primary\",\"evaluation\":{\"timeframe\":\"15m\"},\"get-action\":{\"actionIndex\":1},\"labels\":{\"Problem URL\":\"http://prometheus-server-57f4946cdb-fghkq:9090/graph?g0.expr=histogram_quantile%280.9%2C+sum+by%28le%29+%28rate%28http_response_time_milliseconds_bucket%7Bhandler%3D%22ItemsController.addToCart%22%2Cjob%3D%22carts-sockshop-production-primary%22%7D%5B3m%5D%29%29%29+%3E+1000\\u002 …
```
> fix: Deployment Type in remediation.triggered incompatible with Keptn cloud events

- README.md
Update compatibility matrix to include the two latest releases: 0.9.1 and 0.8.6
> chore: Update compatibility matrix

- .github/workflows/integration-tests.yaml
- updates the JES version in the integration tests to 0.3.0
- adds Keptn 0.19.0 and 0.19.1 to the integration test matrix
Green integration tests: https://github.com/keptn-contrib/prometheus-service/actions/runs/3321320896
> ci: Add Keptn 0.19.0 and 0.19.1 to integration test pipeline, update JES

- chart/templates/serviceaccount.yaml
- chart/values.yaml
https://github.com/keptn-contrib/prometheus-service/issues/391
> fix: ServiceAccount Template generation issue
