- eventhandling/alertEvent.go
- go.mod
- go.sum
> #1694 Added problemUrl to problem payload

- eventhandling/configureEvent.go
Closes https://github.com/keptn-contrib/prometheus-service/issues/57
> Remove debug output of keptn-domain

- deploy/service.yaml
- eventhandling/configureEvent.go
- utils/utils.go
> make scrape path configurable

- .github/workflows/reviewdog.yml
- .github/workflows/tests.yml
- eventhandling/alertEvent.go
- eventhandling/configureEvent.go
- eventhandling/handler.go
- go.mod
- go.sum
- main.go
- reviewdog.yml
> Remove Websocket Communication

- deploy/service.yaml
Moved distributor to same pod as prometheus-service
> Updated deployment manifest

- eventhandling/configureEvent.go
Fixes #80 by setting the correct cloud-event source
> #80 Set proper source for cloud-events

- .github/workflows/CI.yml
This PR fixes GH workflow CI.yml for external contributors
> Fix gh workflow CI.yaml for external contributor

- .github/dependabot.yml
- .github/workflows/CI.yml
* Added dependabot config for automated dependency updates
* Updated CI workflow to use docker login action
> Added dependabot, use docker login action

- README.md
- go.mod
- go.sum
- releasenotes/releasenotes_V0.4.0.md
- releasenotes/releasenotes_develop.md
- releasenotes/releasenotes_develop.md.go
> prepare release v0.4.0

- deploy/service.yaml
Signed-off-by: Florian Bacher <florian.bacher@dynatrace.com>
> Fixed configuration of distributor to avoid port conflict

- deploy/service.yaml
> updated distributer to 0.8.0

- deploy/service.yaml
- releasenotes/releasenotes_V0.4.0.md
> prepare release 0.4.0

- README.md
Signed-off-by: Johannes <johannes.braeuer@dynatrace.com>
> Update of master based on release

- deploy/service.yaml
- main.go
- utils/prometheus.go
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>
Issue- https://github.com/keptn-contrib/prometheus-service/issues/122
> Adding Prometheus SLI functionalities to promtheus-services

- README.md
- deploy/service.yaml
README for prometheus sli service 
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>
> README for prometheus sli service 

- README.md
- deploy/service.yaml
- releasenotes/releasenotes_V0.6.1.md
This PR provides Keptn 0.8.4 compatibility and releases this service in version 0.6.1.
:exclamation: do not merge before Keptn 0.8.4 has been released
> Keptn 0.8.4 compatibility

- README.md
Signed-off-by: jetzlstorfer <juergen.etzlstorfer@dynatrace.com>
> add Keptn 0.8.7 to readme

- .github/workflows/reviewdog.yml
- Dockerfile
- README.md
Signed-off-by: Giovanni Liva <giovanni.liva@dynatrace.com>
> Rebase master

- main.go
- Sets the service name to prometheus-service
Fixes #196
> #196 Set service name to prometheus-service

- .github/workflows/validate-semantic-pr.yml
Adds a workflow for validating semantic PRs
> chore: added workflow for validating semantic PRs

- CODEOWNERS
- README.md
- Adds @christian-kreuzberger-dtx as a codeowner
- Updates README installation instructions
> chore: update codeowners and readme

- gh-actions-scripts/build_helm_chart.sh
Unfortunately I introduced an unneccessary comma with PR https://github.com/keptn-contrib/prometheus-service/pull/222
> build: remove unneeded comma

- .github/workflows/CI.yml
- updates CI pipeline with latest enhancements
> build: Update ci pipeline

- eventhandling/configureEvent.go
- utils/k8s.go
- utils/prometheus.go
Resolves #240 
To try it out, download the Helm Chart artifact from here: https://github.com/keptn-contrib/prometheus-service/actions/runs/1693170173
Extract the ZIP file,
And install it using
```bash
helm upgrade --install -n keptn prometheus-service ./prometheus-service-0.7.3-dev-PR-252.tgz
```
> refactor: reload prometheus configuration without deleting pods

- eventhandling/configureEvent.go
Alerts are useful only to trigger remediations when SLOs are violated.
If no remediation is defined in a stage there is no need to clutter the
prometheus configuration with alerts that will not trigger any recovery
action.
Closes #253 
Signed-off-by: Paolo Chila <paolo.chila@dynatrace.com>
> feat: only add prometheus alerts if remediation.yaml is defined for the stage

- README.md
Update README with the 0.7.3 release, move some sections around
> build: Prepare 0.7.3 release in docs

- .github/actions/unit-tests/action.yml
Signed-off-by: Paolo Chila <paolo.chila@dynatrace.com>
> ci: add gotestsum for better unit tests output

- utils/prometheus/prometheus.go
> feat: Utilize official prometheus api for querying SLI values

- README.md
- TROUBLESHOOTING.md
- eventhandling/configureEvent.go
- go.mod
- go.sum
- Adds custom error message for permission errors (role binding missing)
- Adds `TROUBLESHOOTING.md` file
- Documents role binding error
**Resolves:** #260
> feat: Add role binding error handling

- eventhandling/configureEvent.go
- Tries to improve the SLO expression handling for alerts by removing whitespaces
Fixes #228
> feat(core): Improve SLO expression handling

- README.md
- chart/values.yaml
- go.mod
- go.sum
- skaffold.yaml
- updates the distributor and Keptn dependencies to version 0.15.1
> feat: Upgrade to Keptn 0.15.1

- README.md
Signed-off-by: Raphael Ludwig <raphael.ludwig@dynatrace.com>
> fix(docs): Release version in compatibility matrix

- .github/workflows/integration-tests.yaml
- test/e2e/utils.go
- fixes the integration tests
- improves debug archive logging output
- #338
> fix: Integration tests

- .github/workflows/integration-tests.yaml
Post summary to integration test results
https://github.com/keptn-contrib/prometheus-service/actions/runs/2636218815
> feat: Post integration test summary to GH workflow

- .github/workflows/integration-tests.yaml
- chart/templates/_helpers.tpl
- chart/templates/deployment.yaml
- chart/templates/serviceaccount.yaml
- chart/values.yaml
- test/e2e/podtatohead_test.go
- fixes the broken auto-detection feature (https://github.com/keptn-contrib/prometheus-service/actions/runs/2751194405)
> fix: Auto-detection feature

- README.md
- updates the compatibility matrix for release 0.8.5
> chore: Update Readme.md for release of 0.8.5

- eventhandling/alertEvent.go
- eventhandling/getSliEvent.go
- prometheus_alert.json
- test/e2e/podtatohead_test.go
- test/shipyard/podtatohead.deployment.yaml
> fix: Deployment Type in remediation.triggered incompatible with Keptn cloud events

- CODEOWNERS
Changing Codeowners as I am handing over responsibility of this service towards Keptn maintainers
> chore: Change codeowners

- .github/workflows/integration-tests.yaml
- README.md
- fixes some github actions formatting for set-output
> ci: Minor github actions fixes, update compatibility matrix
